### ISSUE TITLE
Migration to GitBook

### ISSUE THREAD

**Issue by fsuarez6** [crigroup/osrobotics#1]
This issue is for tracking the migration of the [Introduction to Open-Source Robotics](http://osrobotics.org/pages/introduction_osr.html) course from pelican to GitBook.

This is the list of pages along with the preson in charge of the conversion to markdown:
> **Note:** Please click the checkbox once you are done with the page migration.

- [x] [Introduction](https://github.com/crigroup/osrobotics/blob/master/presentation.md) (Francisco)
  - [x] [Overview](https://github.com/crigroup/osrobotics/blob/master/introduction/overview.md) (Francisco)
- [x] [Installation and Setup](https://github.com/crigroup/osrobotics/blob/master/installation/section.md) (Francisco)
  - [x] [Basic tools](https://github.com/crigroup/osrobotics/blob/master/installation/basic_tools.md) (Francisco)
  - [x] [Motion planning: OpenRAVE](https://github.com/crigroup/osrobotics/blob/master/installation/motion_planning.md) (Francisco)
  - [x] [Vision: OpenCV, PCL](https://github.com/crigroup/osrobotics/blob/master/installation/vision.md) (Huy)
  - [x] [System: ROS, Gazebo](https://github.com/crigroup/osrobotics/blob/master/installation/system.md) (Francisco)
- [x] [Manipulator kinematics](https://github.com/crigroup/osrobotics/blob/master/kinematics/section.md) (Cuong)
  - [x] [Introduction](https://github.com/crigroup/osrobotics/blob/master/kinematics/introduction.md) (Cuong)
  - [x] [Forward kinematics](https://github.com/crigroup/osrobotics/blob/master/kinematics/forward.md) (Cuong)
  - [x] [Inverse kinematics](https://github.com/crigroup/osrobotics/blob/master/kinematics/inverse.md) (Cuong)
- [x] [Motion planning](https://github.com/crigroup/osrobotics/blob/master/planning/section.md) (Cuong)
  - [x] [Introduction](https://github.com/crigroup/osrobotics/blob/master/planning/introduction.md) (Cuong)
  - [x] [Path planning](https://github.com/crigroup/osrobotics/blob/master/planning/path_planning.md) (Cuong)
  - [x] [Time-parameterization](https://github.com/crigroup/osrobotics/blob/master/planning/time_parameterization.md) (Cuong)
  - [x] [Post-processing](https://github.com/crigroup/osrobotics/blob/master/planning/post_processing.md) (Cuong)
- [x] [Robot vision](https://github.com/crigroup/osrobotics/blob/master/vision/section.md) (Huy)
  - [x] [Introduction](https://github.com/crigroup/osrobotics/blob/master/vision/introduction.md) (Huy)
  - [x] [2D vision](https://github.com/crigroup/osrobotics/blob/master/vision/vision_2d.md) (Huy)
  - [x] [3D vision](https://github.com/crigroup/osrobotics/blob/master/vision/vision_3d.md) (Huy)
- [x] [System](https://github.com/crigroup/osrobotics/blob/master/system/section.md) (Francisco)
  - [x] [ROS architecture](https://github.com/crigroup/osrobotics/blob/master/system/architecture.md) (Francisco)
  - [x] [Robot simulation in Gazebo](https://github.com/crigroup/osrobotics/blob/master/system/simulation.md) (Francisco)
  - [ ] [Robot vision with ROS](https://github.com/crigroup/osrobotics/blob/master/system/vision.md) (Huy)
- [x] [Force control](https://github.com/crigroup/osrobotics/blob/master/force/section.md) (Hien)
  - [x] [Introduction](https://github.com/crigroup/osrobotics/blob/master/force/introduction.md) (Hien)
  - [x] [Principles of force control](https://github.com/crigroup/osrobotics/blob/master/force/principles.md) (Hien)
  - [x] [Examples](https://github.com/crigroup/osrobotics/blob/master/force/examples.md) (Hien)
- [ ] [Assignments](https://github.com/crigroup/osrobotics/blob/master/assignments/section.md) (Cuong)
  - [x] [Motion planning](https://github.com/crigroup/osrobotics/blob/master/assignments/planning.md) (Francisco)
  - [ ] [Robot vision](https://github.com/crigroup/osrobotics/blob/master/assignments/vision.md) (Huy)

> For inspiration, you can check this tutorial:
> - Gitbook: https://tutorial.djangogirls.org/en/#
> - Source code: https://github.com/DjangoGirls/tutorial

**Comment by quangounet** [comment]
@fsuarez6 Which tool do you suggest to convert pelican (rst) into gitbook format? We should use the same tool.

**Comment by fsuarez6** [comment]
[pandoc](https://pandoc.org/try/) is a great tool. 
The thing is that you need to use it the same way one would use google translator: translate the bulk and then improve/fix the *style*/*grammar*.
> **Warning:** the web pandoc limits the number of characters per conversion, so, make sure it *translates* everything.

Doing the conversion manually is also a good alternative (that's how I did it) and along the way you learn gitbook-markdown for future pages/books.

**Comment by quangounet** [comment]
I recommend using this:
https://pandoc.org/try/ from rst to markdown (pandoc)
For math
- add {% include "../math.md" %} at the beginning of the file
- replace the $ by $$

**Comment by quangounet** [comment]
To convert long chunks of text, it's better to run pandoc from the terminal:
```
sudo apt-get install pandoc
pandoc input.rst -o output.md --atx-headers
```

**Comment by quangounet** [comment]
Migration completed
