### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by quangounet** [crigroup/osrobotics#2]
Seems like there's not a proper way to resize images yet 
https://github.com/GitbookIO/gitbook/issues/1631
This can be very annoying. Any idea?

**Comment by fsuarez6** [comment]
If you *really need* to change the image size, it can be done like this
```
Here is an 200x100 image:

<img src="../assets/controller.png" width="200" height="100" />
```
Another alternative would be to resize the image file itself.

**Comment by quangounet** [comment]
Not very nice :(

**Comment by fsuarez6** [comment]
Agree. 'No choice'. Markdown limitation.
