### ISSUE TITLE
Add panels (or similar) for Example codes, Exercises, etc.

### ISSUE THREAD

**Issue by fsuarez6** [crigroup/osrobotics#4]
From slack:
>@quangounet
>I'd like to add blocks to the Gitbook version, for the Example codes, Exercises, etc

**Comment by fsuarez6** [comment]
@quangounet 
What do you think about this: https://github.com/erixtekila/gitbook-plugin-richquotes?
They look like the blue panel below:
![image](https://user-images.githubusercontent.com/4430326/29508440-24136c2e-8687-11e7-8adc-9c7a91b98713.png)

**Comment by quangounet** [comment]
That looks good. Is it configurable? We'd need a few different colors.

**Comment by fsuarez6** [comment]
Check here for more colors: https://github.com/erixtekila/gitbook-plugin-richquotes

**Comment by fsuarez6** [comment]
In any case, I'm still trying to get the `richquotes` plugin to work

**Comment by quangounet** [comment]
Great! I think this is exactly what we need. Thanks.

**Comment by fsuarez6** [comment]
This has been solved using: [callouts](https://www.npmjs.com/package/gitbook-plugin-callouts)

Check these two definitions for an usage example:
- Book: https://crigroup.gitbooks.io/osrobotics/content/planning/introduction.html
- Source code for the first one:
```
> #### Definition::Obstacle and free configuration space
The subset of $$\mathcal{C}$$ that consists of joint angles values
$$\bfq$$ where the robot collides with the environment or with itself
is called the *obstacle space* and denoted
$$\mathcal{C}_\mathrm{free}$$. The complement of
$$\mathcal{C}_\mathrm{free}$$ is called the *free space* and denoted
$$\mathcal{C}_\mathrm{free}$$.
```
To **add new callouts** check [how I added `definition`](https://github.com/crigroup/osrobotics/blob/2ae9e1068f21a3619997c93573830cd18f9087da/book.json#L18)

**Comment by fsuarez6** [comment]
I just realized the `mathjax` part vanishes :(
Looking into it!

**Comment by quangounet** [comment]
I refreshed and it worked on my computer
