### ISSUE TITLE
Mathjax does not load until the page is refreshed

### ISSUE THREAD

**Issue by quangounet** [crigroup/osrobotics#5]
Mathjax formulae are not loaded on the first page visit. One needs to refresh the page for the formulae to load.
One possible way around is to force the formulae to be statically loaded in SVG (set forceSVG to true in book.json), but this stops the compiling process each  time there's a LaTeX error -> not convenient.

**Comment by fsuarez6** [comment]
I think using the option `forceSVG = true ` is a good approach. In any case, one shouldn't push before building the book locally and therefore the LaTeX error won't go unnotice

**Comment by quangounet** [comment]
These guys have the same problem https://github.com/GitbookIO/plugin-mathjax/issues/34
When forcing SVG output there are other errors (e.g. "Error: TypeError: speech.processExpression is not a function") that I was not able to debug.

**Comment by fsuarez6** [comment]
There is another plugin: https://github.com/GitbookIO/plugin-katex
The problem with `katex` is that it fails when global commands are defined, see this [related issue](https://github.com/GitbookIO/plugin-katex/issues/7), which is something we are doing here: [math.md](https://github.com/crigroup/osrobotics/blame/7e662cae45c15419011fc9cd0abde7fc0c6702cb/math.md)

@quangounet, Let's assume that `katex` doesn't force refreshing the page, are we willing to give-up global commands definitions (e.g. `\newcommand{\bfp}{\boldsymbol{p}}`) ?

**Comment by quangounet** [comment]
I've also looked into KaTeX but apparently it is still not as stable and well supported as Mathjax, in addition to the problem you mentioned. Let's give ourselves a few more days to see whether we can work around this issue in Mathjax (unless the switch is super-easy to try out).

**Comment by quangounet** [comment]
I found a (dirty) workaround: force Mathjax to load by adding the javascript command MathJax.Hub.Queue(["Typeset",MathJax.Hub]), see commit 3ee47e3c8ae70c3639d81032d1b92f8cb9cde7f9

**Comment by fsuarez6** [comment]
Does it mean that for every page that has any kind of math (`$$`) we must include [math.md](https://github.com/crigroup/osrobotics/blame/master/math.md)?

**Comment by fsuarez6** [comment]
In any case, your workaround fixes this issue.

**Comment by quangounet** [comment]
Yes, for now we must include math.md. We can try and find a way to do cleaner includes.

**Comment by jeffrey-cochran** [comment]
I've been looking around to see if this was cleaned up somewhere. Looks like it's still the case that I have to modify each page? That's rough, but thanks for the solution!

**Comment by fsuarez6** [comment]
That's right. The issue is still open: GitbookIO/plugin-mathjax#34
