### ISSUE TITLE
Figures in the book entry point will break the details page

### ISSUE THREAD

**Issue by fsuarez6** [crigroup/osrobotics#6]
Adding figures to the entry point of the book will *break* the [details page](www.gitbook.com/book/crigroup/osrobotics/details):
![image](https://user-images.githubusercontent.com/4430326/29649144-d3654550-88c4-11e7-83f8-d5b72b9e2c26.png)

I think we should roll back to the previous structure:
- Introduction
  - Overview

**Comment by fsuarez6** [comment]
I think the video will have the same problem

**Comment by quangounet** [comment]
What is the "details" page?

**Comment by fsuarez6** [comment]
Check the link

**Comment by quangounet** [comment]
I did but still don't get it

**Comment by fsuarez6** [comment]
It's the book entry point. If someone finds the book here: https://www.gitbook.com/search?q=osrobotics
They will land here: https://www.gitbook.com/book/crigroup/osrobotics/details (The details page)

**Comment by fsuarez6** [comment]
Some examples from other books:
- https://www.gitbook.com/book/frontendmasters/front-end-handbook/details (2799 Starts)
- https://www.gitbook.com/book/0xax/linux-insides/details (2361 Starts)
- https://www.gitbook.com/book/97-things-every-x-should-know/97-things-every-programmer-should-know/details (456 Starts)

**Comment by quangounet** [comment]
We shall use our own domain, so this issue will not appear.
