### ISSUE TITLE
Dead link in Chap 1 - System: Ros, Gazebo

### ISSUE THREAD

**Issue by nicholasadr** [crigroup/osrobotics#8]
![Screenshot from 2020-03-19 15-15-38](https://user-images.githubusercontent.com/10348838/77041127-4643b300-69f4-11ea-8b41-03af07c82d0f.png)

One of the tutorial users reported dead link in the link shown above

**Comment by quangounet** [comment]
Fixed by commit 58191a2e877daea7f3e03fba9c007f53eb8085ff
